#!/usr/bin/env bash
# shellcheck disable=SC2317,SC2059
set -euo pipefail
# shellcheck source=tests/fixtures/test-environment.sh
source "$(dirname "${BASH_SOURCE[0]}")/fixtures/test-environment.sh"
cd "$(dirname "$0")/.."
source ./nx.sh
SUDO=''
# Alpine has /etc/nginx/http.d even in disposable containers. Keep package
# include-dir autodetection inside this fixture instead of the container tree.
eval "$(declare -f install_nginx_official | sed 's@/etc/nginx/http.d@'"$CONF_DIR"'@g')"
root=$(mktemp -d)
trap 'rm -rf "$root"; nx_test_cleanup' EXIT
fail(){ echo "FAIL: $*" >&2; exit 1; }
for mode in first second redirect; do
 (
  printf 'old resolver\n' > "$root/real"; chmod 0640 "$root/real"
  ln -sf real "$root/resolv"
  cp -a "$root/real" "$root/expected"
  printf(){
   case "$mode:$1" in
    'first:# Generated by Nginx-X\nnameserver %s\n'|'second:nameserver %s\n') return 1;;
   esac
   builtin printf "$@"
  }
  if [[ $mode == redirect ]]; then
   mktemp(){ if [[ $# == 0 ]]; then echo "$root"; else command mktemp "$@"; fi; }
  fi
  if write_system_dns "$root/resolv" 1.1.1.1 8.8.8.8; then fail "render $mode accepted"; fi
  [[ -L "$root/resolv" && $(readlink "$root/resolv") == real ]] || fail 'link changed'
  cmp "$root/real" "$root/expected"
  [[ $(stat -c %a "$root/real") == 640 ]] || fail 'mode changed'
  ! compgen -G "$root/resolv.stage.*" >/dev/null || fail 'stage leaked'
 )
done
(
 clear(){ :; }; pause(){ :; }; check_cmd(){ return 1; }; confirm(){ return 0; }
 printf(){ if [[ $1 == 'nameserver %s\n' ]]; then return 1; fi; builtin printf "$@"; }
 NX_RESOLV_CONF="$root/resolv" run_menu_action dns_setup_menu <<< $'1\n0' > "$root/menu.log"
 ! grep -q 'DNS 已更新为' "$root/menu.log" || fail 'menu false success'
)
mkdir "$root/dir"; ln -s dir "$root/dirlink"
for dest in dir dirlink; do
 if write_system_dns "$root/$dest" 1.1.1.1; then fail 'directory accepted'; fi
done
(
 install_managed_file(){ command install -m 0644 "$1" "$2"; mkdir "$root/race"; }
 if write_system_dns "$root/race" 1.1.1.1; then fail 'directory race accepted'; fi
 [[ -z $(ls -A "$root/race") ]] || fail 'stage nested'
 ! compgen -G "$root/race.stage.*" >/dev/null || fail 'race stage leaked'
)
for failure in mv backup reload dangling; do
 (
  ensure_runtime_dependencies(){ :; }; ensure_dirs(){ :; }
  detect_os_id(){ echo alpine; }; detect_pkg_mgr(){ echo apk; }
  check_cmd(){ [[ $1 == rc-service ]]; }
  apk(){ :; }; rc-update(){ :; }; rc-service(){ :; }; ensure_acme_installed(){ :; }
  reload_nginx_safe(){ [[ $failure != reload && $failure != dangling ]]; }
  printf 'default original\n' > "$CONF_DIR/default.conf"; chmod 0640 "$CONF_DIR/default.conf"
  if [[ $failure == dangling ]]; then
   rm "$CONF_DIR/default.conf"; ln -s missing "$CONF_DIR/default.conf"
   printf 'old backup\n' > "$CONF_DIR/default.conf.bak"
   run_menu_action install_nginx_official > "$root/install-dangling.log"
   [[ -L "$CONF_DIR/default.conf" && $(readlink "$CONF_DIR/default.conf") == missing ]]
   [[ $(cat "$CONF_DIR/default.conf.bak") == 'old backup' ]]
   rm "$CONF_DIR/default.conf" "$CONF_DIR/default.conf.bak"
   exit 0
  fi
  if [[ $failure == mv ]]; then mv(){ return 1; }; fi
  if [[ $failure == backup ]]; then printf 'old backup\n' > "$CONF_DIR/default.conf.bak"; fi
  run_menu_action install_nginx_official > "$root/install-$failure.log"
  [[ $(cat "$CONF_DIR/default.conf") == 'default original' ]] || fail 'default lost'
  [[ $(stat -c %a "$CONF_DIR/default.conf") == 640 ]] || fail 'default mode lost'
  ! grep -q 'Nginx 与依赖安装完成' "$root/install-$failure.log" || fail 'install false success'
  if [[ $failure == backup ]]; then [[ $(cat "$CONF_DIR/default.conf.bak") == 'old backup' ]] || fail 'backup overwritten'; rm "$CONF_DIR/default.conf.bak"; fi
 )
done
# BusyBox mv supports -T as well; check the native applet when present (Alpine CI).
if command -v busybox >/dev/null; then
 printf stage > "$root/busy-stage"
 if busybox mv -fT "$root/busy-stage" "$root/dir"; then fail 'BusyBox directory overwrite'; fi
 [[ -f "$root/busy-stage" && -z $(ls -A "$root/dir") ]] || fail 'BusyBox nested stage'
fi
echo 'PASS system DNS render/menu/race and installation default rollback'
